### ISSUE TITLE
Clarify message for unsupported QR code

### ISSUE THREAD

**Issue by LennertDefauw1** [threefoldtech/threefold_connect_wallet#188]
See: https://github.com/threefoldtech/threefold_connect/issues/488

**Comment by ken-de-moor** [comment]
Re-opened

I get the error on a correct QR-scan.

![image](https://user-images.githubusercontent.com/59569757/195339089-ff6ec48d-36e9-4a25-b5ab-4511f74f6a3a.png)

This QR scans on prod with no issue, gives error on staging.
